### PR TITLE
Padding to main content

### PR DESCRIPTION
**Pull request by RochX**
- Add padding the main content so it isn't right next to the sidebar and topbar
- Add welcome messages to the home page

### CODE REVIEW

**Review by harshsepi0l — COMMENTED** [review]
I have a "Welcome, [Student.name]!" in Calendar.jsx. Take a look at it and let me know.  I want to address having a welcome in the calendar and just changing it to: "[Student.name]'s schedule" or something along those lines.

**Comment by RochX** [comment]
Accidentally clicked close pull request oops

**Comment by harshsepi0l** [comment]
Carousel's image size parameters are fixed!

**Review by harshsepi0l — COMMENTED** [review]
Everything looks good!

**Review by harshsepi0l — APPROVED** [review]
Reviewing finalized and approved

**Pull request merged**
